#pragma once

class GLAppVars
{
public:
	enum UBOBindingPoints
	{
		UBOBindingPoints_MODEL_MATERIAL_UBO_BINDING_POINT = 0,
		UBOBindingPoints_NUM_ENGINE_RESERVED_UBO_BINDING_POINTS
	};

	enum TextureUnits
	{
		TextureUnits_DFV_TEXTURE = 0,
		TextureUnits_CLUSTERED_LIGHTING_GRID_TEXTURE,
		TextureUnits_CLUSTERED_LIGHTING_LIGHT_ID_TEXTURE,
		TextureUnits_MODEL_1_COMPONENT_TEXTURE_ARRAY,
		TextureUnits_MODEL_3_COMPONENT_TEXTURE_ARRAY,
		TextureUnits_NUM_ENGINE_RESERVED_TEXTURE_UNITS
	};
};